FName=input('Enter First Name:')
LName=input('Enter Last Name:')
Addy=input('Enter Address:')
City=input('Enter City:')
State=input('Enter State:')
Postal=input('Enter Postal Code:')
print('Name:', FName, LName)
print('Address:', Addy)
print(City,',', State, Postal)
